### PR TITLE
Added serach bar in CA an schloarship

### PR DESCRIPTION
**Pull request by avishekchoudhary**
# Description

**> If you are going merge my PR , Please label it as 'hacktoberfest-accepted',as it showing that your repo is not  participating in Hacktoberfest**

Added search bar in CA program.html and scholarship.html.I Added a form tag inside li tag in nav bar.Css for search bar has been added to style.css with heading "searchbar"  and also added some change in media queries related only to form tag/search bar.
Fixes # (9)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ✔] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ✔] My code follows the style guidelines of this project
- [✔ ] I have performed a self-review of my own code
- [✔ ] I have commented my code, particularly in hard-to-understand areas
- [✔ ] I have made corresponding changes to the documentation
- [ ✔] My changes generate no new warnings
- [✔ ] I have added tests that prove my fix is effective or that my feature works
- [ ✔] New and existing unit tests pass locally with my changes
- [✔ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lakshyatyagi24** [comment]
Please share the screenshot or screen recording of your work output for better review

**Comment by avishekchoudhary** [comment]
> Please share the screenshot or screen recording of your work output for better review


I have sent you a video recording on your instagram handle.My ig handle is choudhary_avishek.

**Comment by lakshyatyagi24** [comment]
@avishekchoudhary it is not looking same on website [https://scodein.tech/Scodex/CA%20program.html](https://scodein.tech/Scodex/CA%20program.html) as you shared me on insta

**Comment by avishekchoudhary** [comment]
> @avishekchoudhary it is not looking same on website https://scodein.tech/Scodex/CA%20program.html as you shared me on insta

It's working fine.I think this website is not mobile responsive.Here I'm sending you a screenshot how it looks on my mobile phone.
Screenshot_2020-10-09-03-10-35-232_com android chrome

**Comment by lakshyatyagi24** [comment]
Ok Team will check it till then i am removing the labels to make it safe after reviewing the issue we will again label it with hacktoberfest

**Comment by avishekchoudhary** [comment]
> Ok Team will check it till then i am removing the labels to make it safe after reviewing the issue we will again label it with hacktoberfest

Could you please assure some certain time for reviewing process.As it would be very helpul for me .

**Comment by lakshyatyagi24** [comment]
within 24 hours we will review it

**Comment by avishekchoudhary** [comment]
> within 24 hours we will review it

Ok.

**Comment by avishekchoudhary** [comment]
Any updates regarding reviewing process.

**Comment by lakshyatyagi24** [comment]
Sorry your PR is not accepted towards Hacktoberfest

**Comment by avishekchoudhary** [comment]
> Sorry your PR is not accepted towards Hacktoberfest

Ok

**Pull request merged**
